#######################################################################
#		DOCKERFILE PARA LA CALCULADORA			      #
#######################################################################

FROM oracle/glassfish

ADD ["servicios.war","$GLASSFISH_HOME/glassfish/domains/domain1/autodeploy/"]
